apiVersion: v1
kind: Service
metadata:
  name: new-anime-service  # Name for your service
spec:
  type: NodePort  # Service type as NodePort
  selector:
    app: new-anime  # Matches pods with the label
  ports:
  - protocol: TCP  # Protocol
    port: 3000  # External port to access the service
    targetPort: 80  # Port on the pods that the service will route traffic to
