apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-anime-deployment  # Name for your deployment
spec:
  replicas: 2  # Number of pods (2 in this case)
  selector:
    matchLabels:
      app: new-anime  # Label to identify pods belonging to this deployment
  template:
    metadata:
      labels:
        app: new-anime  # Labels for the pods in the deployment
    spec:
      containers:
      - name: new-anime  # Container name
        image: aspper/new-anime:latest  # Your image reference
        # Add any container specific configurations here (e.g., ports, resources)
        ports:
        - containerPort: 80  # Port your application listens on

